/*
Author: Arkadiusz Sas
Modified: 2019-03-14
Database: PostgreSQL 10
*/

CREATE TABLE DOCTOR(
    DOCTOR_ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL_ADDRESS VARCHAR(254),
    PHONE_NUMBER VARCHAR(15),
    STREET VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    POSTAL_CODE VARCHAR(10) NOT NULL,
    SALARY INTEGER NOT NULL
);

CREATE TABLE PATIENT(
    PATIENT_ID BIGSERIAL PRIMARY KEY,
    DOCTOR_ID INTEGER REFERENCES DOCTOR(DOCTOR_ID),
    FILE_ID INTEGER NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL_ADDRESS VARCHAR(254),
    PHONE_NUMBER VARCHAR(15),
    STREET VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    POSTAL_CODE VARCHAR(10) NOT NULL,
    FIRST_VISIT_DATE DATE NOT NULL,
    LAST_VISIT_DATE DATE NOT NULL,
    IS_INSURANCE BOOLEAN NOT NULL
);

/*
    examples of replete insert schemas
    
    INSERT INTO DOCTOR (DOCTOR_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL_ADDRESS, PHONE_NUMBER, STREET, CITY, POSTAL_CODE, SALARY) 
    VALUES (1, 'George', 'Newman', '1974-02-22', 'george.newman@eclinic.com', '202-555-0103', '454 Front St.', 'New York', '11208', 150000);

    INSERT INTO PATIENT(PATIENT_ID, DOCTOR_ID, FILE_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, EMAIL_ADDRESS, PHONE_NUMBER, STREET, CITY, POSTAL_CODE, 
        FIRST_VISIT_DATE, LAST_VISIT_DATE, IS_INSURANCE) 
    VALUES (1, 1, 1000, 'Russell', 'Mancini', '1994-02-25', 'russell.mancini@inbox.com', '674-345-8585', '690 Pineknoll Rd.', 'New York', '10452',
        '2019-03-14', '2019-03-14', TRUE);
*/